#!/home/gitpod/.pyenv/shims/python3
import boto3
from botocore.exceptions import ClientError
import requests
import json

url = "https://sqs.us-east-1.amazonaws.com/440848399208/xxn3na"
sqs = boto3.client("sqs")
